apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: iperf3server
  name: iperf3server
spec:
  ports:
    - name: "iperf3"
      port: 5201
      targetPort: 5201
  selector:
    io.kompose.service: iperf3server
